// <auto-generated />
using BakeryShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BakeryShop.Data.Migrations
{
    [DbContext(typeof(BakeryShopContext))]
    partial class BakeryShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("BakeryShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageFileName");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Carrot Cake Desc",
                            ImageName = "carrot_cake.jpg",
                            Name = "Carrot Cake",
                            Price = 20m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lemon Tart Desc",
                            ImageName = "lemon_tart.jpg",
                            Name = "Lemon Tart",
                            Price = 30m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cup Cakes Desc",
                            ImageName = "cupcakes.jpg",
                            Name = "Cup Cakes",
                            Price = 50m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bread Cakes Desc",
                            ImageName = "bread.jpg",
                            Name = "Bread",
                            Price = 15m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
